# WeatherPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time
from scipy.stats import linregress
import random

# Import API key
from api_keys import weather_api_key

# Incorporated citipy to determine city based on latitude and longitude
from citipy import citipy

# Output File (CSV)
output_data_file = "output_data/cities.csv"

# Range of latitudes and longitudes
lat_range = (-90, 90)
lng_range = (-180, 180)

## Generate Cities List

In [2]:
# List for holding lat_lngs and cities
lat_lngs = []
cities = []

# Create a set of random lat and lng combinations
lats = np.random.uniform(lat_range[0], lat_range[1], size=1500)
lngs = np.random.uniform(lng_range[0], lng_range[1], size=1500)
lat_lngs = zip(lats, lngs)

# Identify nearest city for each lat, lng combination
for lat_lng in lat_lngs:
    city = citipy.nearest_city(lat_lng[0], lat_lng[1]).city_name
    
    # If the city is unique, then add it to a our cities list
    if city not in cities:
        cities.append(city)

# Print the city count to confirm sufficient count
len(cities)
print(cities)

['takoradi', 'cape town', 'husavik', 'ushuaia', 'rikitea', 'kapaa', 'hermanus', 'provideniya', 'amapa', 'abu dhabi', 'bluff', 'punta arenas', 'bathsheba', 'makung', 'balimo', 'phangnga', 'leh', 'karratha', 'ilulissat', 'kaitangata', 'illoqqortoormiut', 'luderitz', 'nizhneyansk', 'arraial do cabo', 'samarai', 'oktyabrskoye', 'korla', 'santa rosa', 'lavrentiya', 'kaspiysk', 'bethel', 'port blair', 'karakendzha', 'wanaka', 'attawapiskat', 'busselton', 'salalah', 'panzos', 'yellowknife', 'longlac', 'kurmanayevka', 'carnarvon', 'cidreira', 'taolanaro', 'esperance', 'muros', 'lebu', 'along', 'bambous virieux', 'mareeba', 'kavieng', 'hofn', 'grand river south east', 'sumenep', 'port alfred', 'xai-xai', 'coos bay', 'albany', 'new norfolk', 'puerto ayora', 'cabo san lucas', 'hambantota', 'kodiak', 'atuona', 'palkino', 'faanui', 'katsuura', 'namatanai', 'rajauri', 'sisimiut', 'fort nelson', 'vangaindrano', 'vardo', 'inhapim', 'glendive', 'mahebourg', 'sindand', 'sedan', 'chepen', 'tuktoyaktuk', 'saint-philippe', 'maceio', 'kysyl-syr', 'bredasdorp', 'east london', 'port elizabeth', 'kemijarvi', 'naze', 'sibolga', 'mataura', 'upernavik', 'novyy urengoy', 'victoria', 'wahiawa', 'nanakuli', 'langfang', 'budogoshch', 'sao filipe', 'saskylakh', 'castro', 'tasiilaq', 'sobolevo', 'hilo', 'oistins', 'belushya guba', 'oranjestad', 'jamestown', 'sharya', 'geraldton', 'san ramon', 'butaritari', 'mitchell', 'ous', 'lompoc', 'seabra', 'saint george', 'yandoon', 'umzimvubu', 'shingu', 'darhan', 'talnakh', 'avarua', 'ipixuna', 'nome', 'manoel urbano', 'shache', 'soyo', 'potsdam', 'ciudad bolivar', 'gazojak', 'atambua', 'oreanda', 'samusu', 'khuzhir', 'vaini', 'beloha', 'borda da mata', 'emba', 'san matias', 'antofagasta', 'vostok', 'anshun', 'ostrovnoy', 'gander', 'clarence town', 'zharkent', 'hobyo', 'wewak', 'southbridge', 'jalalpur', 'harper', 'nizhnyaya omka', 'isangel', 'saint anthony', 'barentsburg', 'anadyr', 'alyangula', 'chokurdakh', 'druzhba', 'balkhash', 'filadelfia', 'temaraia', 'natal', 'robe', 'rudnya', 'barrow', 'fortuna', 'nanortalik', 'pocone', 'castro-urdiales', 'cherskiy', 'waipawa', 'flin flon', 'madang', 'mindelo', 'narsaq', 'amderma', 'tanout', 'angoche', 'vrangel', 'lipany', 'bandarbeyla', 'truth or consequences', 'ugoofaaru', 'merauke', 'khorramshahr', 'valera', 'wazzan', 'chuy', 'prince rupert', 'osvaldo cruz', 'pakxan', 'svetlyy', 'tondano', 'qandala', 'norman wells', 'qaanaaq', 'vila franca do campo', 'touros', 'iralaya', 'thompson', 'palabuhanratu', 'avera', 'cairns', 'bubaque', 'tiksi', 'wufeng', 'vila velha', 'mar del plata', 'broome', 'kaohsiung', 'bontang', 'kupang', 'port lincoln', 'flinders', 'dunedin', 'gladstone', 'biltine', 'beyneu', 'khandbari', 'dikson', 'muravlenko', 'lindenberg', 'marzuq', 'mys shmidta', 'kamaishi', 'alexandria', 'sentyabrskiy', 'oktyabrskiy', 'jeremie', 'kunya', 'camalu', 'padang', 'bairiki', 'brae', 'deputatskiy', 'dandong', 'itaquyry', 'ixtapa', 'birao', 'olinda', 'reus', 'constitucion', 'yulara', 'bull savanna', 'boyolangu', 'khatanga', 'jinchang', 'baijiantan', 'muli', 'sacalum', 'dingle', 'sao joao da barra', 'trinidad', 'rawson', 'nikolskoye', 'lubango', 'lagoa', 'tromso', 'road town', 'bandrele', 'guerrero negro', 'pafos', 'codrington', 'longyearbyen', 'adrar', 'la serena', 'sabha', 'buin', 'alofi', 'tura', 'orotukan', 'loviisa', 'hobart', 'manacor', 'norsup', 'marystown', 'mitsamiouli', 'beroroha', 'san quintin', 'beamsville', 'quatre cocos', 'armidale', 'damavand', 'tawkar', 'saleaula', 'tazovskiy', 'iquitos', 'bam', 'atar', 'kazalinsk', 'san lawrenz', 'syracuse', 'loukhi', 'yomitan', 'lozova', 'twentynine palms', 'canar', 'gold coast', 'mancio lima', 'ponta do sol', 'kemise', 'boshnyakovo', 'santa cruz', 'chicama', 'sursk', 'tsihombe', 'karauzyak', 'yahotyn', 'ortona', 'tsentralnyy', 'georgetown', 'ribeira grande', 'ulaangom', 'vaitupu', 'kaspi', 'kaeo', 'felidhoo', 'gat', 'luena', 'aquiraz', 'vestmannaeyjar', 'faya', 'cervo', 'skibbereen', 'kormilovka', 'xuddur', 'batavia', 'te anau', 'bengkulu', 'sao felix do xingu', 'tunxi', 'sukhothai', 'poum', 'opuwo', 'ulladulla', 'severo-kurilsk', 'halalo', 'mulege', 'mangrol', 'plettenberg bay', 'bonavista', 'forbes', 'chingirlau', 'marcona', 'tecoanapa', 'phan thiet', 'jawhar', 'sept-iles', 'solovetskiy', 'baculin', 'saldanha', 'khonuu', 'schkeuditz', 'kruisfontein', 'mullaitivu', 'denpasar', 'carutapera', 'ajaigarh', 'odesskoye', 'umm kaddadah', 'saint-augustin', 'honiara', 'ikryanoye', 'russell', 'hualmay', 'buchanan', 'rundu', 'axim', 'champerico', 'hami', 'eenhana', 'potiskum', 'celestun', 'verkhoshizhemye', 'kondinskoye', 'disraeli', 'wageningen', 'coahuayana', 'erzin', 'itarema', 'toguchin', 'pevek', 'jijiga', 'ambilobe', 'kafanchan', 'jizan', 'babu', 'sitka', 'nemuro', 'klaksvik', 'hithadhoo', 'turukhansk', 'okmulgee', 'saint-georges', 'bilibino', 'altay', 'berlevag', 'muzquiz', 'mantua', 'ilam', 'praia da vitoria', 'cacequi', 'pazaric', 'ayan', 'shelton', 'torbay', 'koslan', 'san ciro de acosta', 'tilichiki', 'rio gallegos', 'hoshcha', 'buala', 'lac du bonnet', 'nguiu', 'sydney', 'kloulklubed', 'alice springs', 'bani', 'grand-bourg', 'pho chai', 'ferndale', 'timbiqui', 'taltal', 'waingapu', 'broken hill', 'wulanhaote', 'arkansas city', 'asau', 'jacareacanga', 'ylojarvi', 'lao cai', 'bolgatanga', 'lufilufi', 'okhotsk', 'daru', 'lolua', 'krasnoselkup', 'kitimat', 'jacqueville', 'walvis bay', 'araouane', 'yuzhno-kurilsk', 'nizhniy kuranakh', 'jumla', 'nantucket', 'kango', 'viligili', 'goderich', 'moranbah', 'port hardy', 'ahipara', 'farah', 'korhogo', 'college', 'linares', 'biggar', 'xiongshi', 'heythuysen', 'point fortin', 'leningradskiy', 'hvide sande', 'ngama', 'bowen', 'ovalle', 'ayagoz', 'nakapiripirit', 'hayvoron', 'lesnoy', 'talaya', 'andrews', 'barcelos', 'kyshtovka', 'seoul', 'grand forks', 'guarare', 'hihifo', 'fort walton beach', 'najran', 'bilecik', 'clyde river', 'bardiyah', 'svetlogorsk', 'barraute', 'eufaula', 'aklavik', 'qui nhon', 'itoman', 'tabiauea', 'acapulco', 'raudeberg', 'sangar', 'nuevitas', 'celica', 'mul', 'farmington', 'koungheul', 'llanes', 'pangnirtung', 'takayama', 'angoram', 'haibowan', 'souillac', 'ancud', 'boende', 'saint-raymond', 'soe', 'san cristobal', 'airai', 'belaya gora', 'mrirt', 'zhigansk', 'belyy yar', 'barra patuca', 'hirara', 'xichang', 'pisco', 'anloga', 'los llanos de aridane', 'lorengau', 'fairbanks', 'karimganj', 'tikhvin', 'maningrida', 'fantanele', 'innisfail', 'tidore', 'trairi', 'prestea', 'mananjary', 'olivet', 'canas', 'labuhan', 'dauphin', 'wanning', 'vredendal', 'cayenne', 'seryshevo', 'meulaboh', 'mount gambier', 'cabedelo', 'safford', 'ozgon', 'zhangye', 'kahului', 'quelimane', 'grimma', 'pauini', 'koster', 'gondanglegi', 'vydrino', 'onalaska', 'necochea', 'bud', 'verkhnevilyuysk', 'knysna', 'paracatu', 'pithora', 'jambi', 'otavi', 'chimoio', 'mocuba', 'crowley', 'andros town', 'coquimbo', 'pimenta bueno', 'bur gabo', 'amahai', 'altamont', 'eyl', 'lugovoy', 'tacna', 'girona', 'alquizar', 'saint joseph', 'penticton', 'haines junction', 'dubbo', 'cangucu', 'zafarwal', 'kimbe', 'galle', 'namibe', 'colac', 'mbanza-ngungu', 'asayita', 'inta', 'hasaki', 'kolvereid', 'tricase', 'tabuk', 'kadoma', 'saryg-sep', 'byron bay', 'feijo', 'iqaluit', 'port macquarie', 'chapais', 'hailey', 'leninskoye', 'yanan', 'quang ngai', 'isabela', 'saint-pierre', 'murray bridge', 'moree', 'hovd', 'tonantins', 'ipswich', 'bayan', 'hanchuan', 'isiro', 'aksha', 'nanma', 'sedro-woolley', 'gandra', 'miraflores', 'jobat', 'rincon', 'baruun-urt', 'sibu', 'kununurra', 'puerto escondido', 'zemio', 'linxia', 'shadrinsk', 'antalaha', 'tigil', 'jaru', 'wahran', 'mana', 'alghero', 'srednekolymsk', 'port keats', 'odweyne', 'arman']

### Perform API Calls
* Perform a weather check on each city using a series of successive API calls.
* Include a print log of each city as it'sbeing processed (with the city number and city name).

In [3]:
url = "http://api.openweathermap.org/data/2.5/weather?"
units = "metric"

query_url = f"{url}appid={weather_api_key}&units={units}&q="

test_url = query_url + "cayenne"
print(test_url)

http://api.openweathermap.org/data/2.5/weather?appid=89d9c63228dc91659679aaceda16c499&units=metric&q=cayenne

In [4]:
#I was getting a API calling error when I tried to do 500, 300 was the only way I could make it work
#cities3 = random.sample(cities, 500)
cities3 = random.sample(cities, 300)
print(cities3)

['te anau', 'hovd', 'berlevag', 'cangucu', 'asau', 'labuhan', 'loukhi', 'wahran', 'cervo', 'pho chai', 'moree', 'hanchuan', 'hobart', 'zemio', 'krasnoselkup', 'fort nelson', 'bonavista', 'muzquiz', 'southbridge', 'armidale', 'sedro-woolley', 'madang', 'antalaha', 'hasaki', 'wanaka', 'atambua', 'saldanha', 'sobolevo', 'leh', 'port lincoln', 'tsihombe', 'kununurra', 'honiara', 'bur gabo', 'amapa', 'kitimat', 'quatre cocos', 'anshun', 'sydney', 'kazalinsk', 'mocuba', 'isiro', 'bandrele', 'pangnirtung', 'arkansas city', 'chuy', 'brae', 'nikolskoye', 'acapulco', 'linxia', 'jeremie', 'chicama', 'andros town', 'rudnya', 'viligili', 'galle', 'dikson', 'osvaldo cruz', 'saleaula', 'sharya', 'odesskoye', 'abu dhabi', 'damavand', 'marzuq', 'chokurdakh', 'goderich', 'zhangye', 'svetlyy', 'rajauri', 'andrews', 'lipany', 'jijiga', 'asayita', 'adrar', 'batavia', 'jamestown', 'cairns', 'langfang', 'sibu', 'vardo', 'san cristobal', 'tigil', 'merauke', 'lao cai', 'tondano', 'celestun', 'llanes', 'tidore', 'vredendal', 'tilichiki', 'nguiu', 'hailey', 'kemijarvi', 'itaquyry', 'wulanhaote', 'punta arenas', 'sao joao da barra', 'palabuhanratu', 'karimganj', 'iquitos', 'shingu', 'dubbo', 'lagoa', 'saint joseph', 'sept-iles', 'phangnga', 'seoul', 'mar del plata', 'kolvereid', 'clarence town', 'lesnoy', 'port alfred', 'hirara', 'kaeo', 'ulaangom', 'sao filipe', 'mahebourg', 'mancio lima', 'alice springs', 'mitchell', 'amahai', 'kodiak', 'xichang', 'buala', 'kaohsiung', 'okmulgee', 'inta', 'ambilobe', 'iqaluit', 'seryshevo', 'jawhar', 'yahotyn', 'bairiki', 'husavik', 'kloulklubed', 'jacareacanga', 'gander', 'kunya', 'maningrida', 'gladstone', 'kavieng', 'ilam', 'saryg-sep', 'vangaindrano', 'butaritari', 'lorengau', 'itarema', 'koungheul', 'yandoon', 'haibowan', 'angoche', 'koster', 'dandong', 'truth or consequences', 'pevek', 'luderitz', 'coahuayana', 'olivet', 'coos bay', 'cayenne', 'luena', 'kysyl-syr', 'alyangula', 'deputatskiy', 'tuktoyaktuk', 'druzhba', 'rawson', 'bathsheba', 'padang', 'kaspi', 'quang ngai', 'kango', 'kondinskoye', 'praia da vitoria', 'barcelos', 'makung', 'san lawrenz', 'zharkent', 'longlac', 'qandala', 'eufaula', 'antofagasta', 'dingle', 'bilibino', 'bardiyah', 'hofn', 'yomitan', 'poum', 'flin flon', 'aquiraz', 'twentynine palms', 'grand forks', 'port hardy', 'shadrinsk', 'odweyne', 'sisimiut', 'port keats', 'erzin', 'port blair', 'pocone', 'oktyabrskoye', 'nome', 'angoram', 'wazzan', 'norsup', 'saint george', 'marystown', 'bowen', 'ushuaia', 'oistins', 'narsaq', 'inhapim', 'haines junction', 'iralaya', 'farah', 'svetlogorsk', 'touros', 'maceio', 'meulaboh', 'xiongshi', 'beloha', 'boende', 'pisco', 'baculin', 'plettenberg bay', 'souillac', 'tunxi', 'torbay', 'budogoshch', 'xai-xai', 'cidreira', 'hithadhoo', 'saint-augustin', 'cacequi', 'yuzhno-kurilsk', 'grimma', 'ajaigarh', 'karakendzha', 'wewak', 'belyy yar', 'provideniya', 'hihifo', 'kruisfontein', 'ayagoz', 'nantucket', 'baruun-urt', 'gandra', 'pithora', 'shache', 'moranbah', 'kormilovka', 'leninskoye', 'ayan', 'kamaishi', 'altay', 'san matias', 'mulege', 'lufilufi', 'nemuro', 'jalalpur', 'mana', 'road town', 'marcona', 'albany', 'trairi', 'trinidad', 'kadoma', 'santa rosa', 'coquimbo', 'gazojak', 'boyolangu', 'camalu', 'chingirlau', 'palkino', 'gat', 'takoradi', 'ovalle', 'penticton', 'heythuysen', 'bam', 'khorramshahr', 'takayama', 'tricase', 'wageningen', 'biggar', 'mys shmidta', 'sibolga', 'norman wells', 'itoman', 'barrow', 'phan thiet', 'lubango', 'nizhneyansk', 'gold coast', 'busselton', 'quelimane', 'leningradskiy', 'codrington', 'la serena', 'bayan']

In [5]:
temp = []
lat = []
lon = []
temp = []
humidity = []
cloud = []
wind = []
city_count = 0
citiesFinal = []

# Loop through the list of cities and perform a request for data on each
for city in cities3:
    response = requests.get(query_url + city).json()
    try:
        lat.append(response['coord']['lat'])
        lon.append(response['coord']['lon'])
        temp.append(response['main']['temp'])
        humidity.append(response['main']['humidity'])
        cloud.append(response['clouds']['all'])
        wind.append(response['wind']['speed'])
        city_count +=1
        citiesFinal.append(city)
        print(city + " "+ str(city_count))
    except:
        pass

te anau 1
hovd 2
berlevag 3
cangucu 4
asau 5
labuhan 6
loukhi 7
cervo 8
pho chai 9
moree 10
hanchuan 11
hobart 12
zemio 13
krasnoselkup 14
fort nelson 15
bonavista 16
southbridge 17
armidale 18
sedro-woolley 19
madang 20
antalaha 21
hasaki 22
wanaka 23
atambua 24
saldanha 25
sobolevo 26
leh 27
port lincoln 28
kununurra 29
honiara 30
amapa 31
kitimat 32
quatre cocos 33
anshun 34
sydney 35
mocuba 36
isiro 37
bandrele 38
pangnirtung 39
arkansas city 40
chuy 41
brae 42
nikolskoye 43
acapulco 44
linxia 45
jeremie 46
chicama 47
andros town 48
rudnya 49
galle 50
dikson 51
osvaldo cruz 52
sharya 53
odesskoye 54
abu dhabi 55
damavand 56
marzuq 57
chokurdakh 58
goderich 59
zhangye 60
svetlyy 61
rajauri 62
andrews 63
lipany 64
jijiga 65
adrar 66
batavia 67
jamestown 68
cairns 69
langfang 70
sibu 71
vardo 72
san cristobal 73
tigil 74
merauke 75
lao cai 76
tondano 77
celestun 78
llanes 79
vredendal 80
tilichiki 81
hailey 82
kemijarvi 83
itaquyry 84
punta arenas 85
sao joao da barra 86
karimganj 87
iquitos 88
shingu 89
dubbo 90
lagoa 91
saint joseph 92
sept-iles 93
phangnga 94
seoul 95
mar del plata 96
kolvereid 97
clarence town 98
lesnoy 99
port alfred 100
hirara 101
kaeo 102
ulaangom 103
sao filipe 104
mahebourg 105
mancio lima 106
alice springs 107
mitchell 108
amahai 109
kodiak 110
xichang 111
buala 112
kaohsiung 113
okmulgee 114
inta 115
ambilobe 116
iqaluit 117
seryshevo 118
jawhar 119
yahotyn 120
bairiki 121
husavik 122
kloulklubed 123
jacareacanga 124
gander 125
kunya 126
maningrida 127
gladstone 128
kavieng 129
ilam 130
saryg-sep 131
vangaindrano 132
butaritari 133
lorengau 134
itarema 135
koungheul 136
angoche 137
koster 138
dandong 139
truth or consequences 140
pevek 141
luderitz 142
coahuayana 143
olivet 144
coos bay 145
cayenne 146
luena 147
kysyl-syr 148
alyangula 149
deputatskiy 150
tuktoyaktuk 151
druzhba 152
rawson 153
bathsheba 154
padang 155
kaspi 156
quang ngai 157
kango 158
kondinskoye 159
praia da vitoria 160
barcelos 161
san lawrenz 162
zharkent 163
qandala 164
eufaula 165
antofagasta 166
dingle 167
bilibino 168
bardiyah 169
hofn 170
poum 171
flin flon 172
aquiraz 173
twentynine palms 174
grand forks 175
port hardy 176
shadrinsk 177
odweyne 178
sisimiut 179
port keats 180
erzin 181
port blair 182
pocone 183
oktyabrskoye 184
nome 185
angoram 186
norsup 187
saint george 188
marystown 189
bowen 190
ushuaia 191
oistins 192
narsaq 193
inhapim 194
haines junction 195
iralaya 196
farah 197
svetlogorsk 198
touros 199
maceio 200
meulaboh 201
beloha 202
boende 203
pisco 204
baculin 205
plettenberg bay 206
souillac 207
torbay 208
budogoshch 209
xai-xai 210
cidreira 211
hithadhoo 212
saint-augustin 213
cacequi 214
yuzhno-kurilsk 215
grimma 216
ajaigarh 217
wewak 218
belyy yar 219
provideniya 220
kruisfontein 221
ayagoz 222
nantucket 223
baruun-urt 224
gandra 225
pithora 226
shache 227
moranbah 228
kormilovka 229
leninskoye 230
ayan 231
kamaishi 232
altay 233
san matias 234
mulege 235
lufilufi 236
nemuro 237
jalalpur 238
mana 239
road town 240
albany 241
trairi 242
trinidad 243
kadoma 244
santa rosa 245
coquimbo 246
gazojak 247
boyolangu 248
camalu 249
chingirlau 250
palkino 251
gat 252
takoradi 253
ovalle 254
penticton 255
heythuysen 256
bam 257
khorramshahr 258
takayama 259
tricase 260
wageningen 261
biggar 262
sibolga 263
norman wells 264
itoman 265
barrow 266
phan thiet 267
lubango 268
gold coast 269
busselton 270
quelimane 271
leningradskiy 272
codrington 273
la serena 274
bayan 275

In [6]:
len(wind)

275

### Convert Raw Data to DataFrame
* Export the city data into a .csv.
* Display the DataFrame

In [16]:
dict = {"city": citiesFinal,
        "lat": lat,
        "long": lon,
        "temp": temp,
        "humidity": humidity,
        "cloud": cloud,
        "wind": wind
}
        
df = pd.DataFrame(dict)
df

              city    lat    long   temp  humidity  cloud  wind
0          te anau -45.42  167.72   9.01        66     69  4.13
1             hovd  48.01   91.64   4.48        33      0  1.77
2         berlevag  70.86   29.09   2.52        91    100  2.60
3          cangucu -31.39  -52.68  14.44        94      0  1.48
4             asau  46.43   26.40   3.25        80     90  1.00
..             ...    ...     ...    ...       ...    ...   ...
270      quelimane -17.88   36.89  25.00        94     20  1.50
271  leningradskiy  69.38  178.42 -13.00        89     16  3.86
272     codrington -38.27  141.97  16.60        57     87  3.36
273      la serena -29.91  -71.25  14.00        93      9  2.10
274          bayan  46.08  127.40  20.00        28    100  7.14

[275 rows x 7 columns]

In [18]:
df.describe()

              lat        long        temp    humidity       cloud        wind
count  275.000000  275.000000  275.000000  275.000000  275.000000  275.000000
mean    19.430182   30.142000   15.639964   67.738182   50.309091    3.335709
std     33.053420   90.612133   11.760892   21.363482   37.420413    2.295547
min    -54.800000 -173.300000  -20.000000    1.000000    0.000000    0.210000
25%     -8.790000  -53.725000    8.115000   54.000000   11.500000    1.500000
50%     24.870000   33.950000   17.120000   73.000000   47.000000    2.950000
75%     47.935000  112.050000   25.000000   83.000000   89.500000    4.600000
max     73.510000  178.420000   37.000000  100.000000  100.000000   11.340000

## Inspect the data and remove the cities where the humidity > 100%.
----
Skip this step if there are no cities that have humidity > 100%.

In [19]:
#  Get the indices of cities that have humidity over 100%.
indexNames = df[ df['humidity']==100].index

In [20]:
df.drop(indexNames, inplace=True)

In [22]:
df.reset_index()

     index           city    lat    long   temp  humidity  cloud  wind
0        0        te anau -45.42  167.72   9.01        66     69  4.13
1        1           hovd  48.01   91.64   4.48        33      0  1.77
2        2       berlevag  70.86   29.09   2.52        91    100  2.60
3        3        cangucu -31.39  -52.68  14.44        94      0  1.48
4        4           asau  46.43   26.40   3.25        80     90  1.00
..     ...            ...    ...     ...    ...       ...    ...   ...
266    270      quelimane -17.88   36.89  25.00        94     20  1.50
267    271  leningradskiy  69.38  178.42 -13.00        89     16  3.86
268    272     codrington -38.27  141.97  16.60        57     87  3.36
269    273      la serena -29.91  -71.25  14.00        93      9  2.10
270    274          bayan  46.08  127.40  20.00        28    100  7.14

[271 rows x 8 columns]

In [12]:
# Make a new DataFrame equal to the city data to drop all humidity outliers by index.
# Passing "inplace=False" will make a copy of the city_data DataFrame, which we call "clean_city_data".

In [13]:
# Extract relevant fields from the data frame


# Export the City_Data into a csv

## Plotting the Data
* Use proper labeling of the plots using plot titles (including date of analysis) and axes labels.
* Save the plotted figures as .pngs.

## Latitude vs. Temperature Plot

## Latitude vs. Humidity Plot

## Latitude vs. Cloudiness Plot

## Latitude vs. Wind Speed Plot

## Linear Regression

In [14]:
# OPTIONAL: Create a function to create Linear Regression plots

In [15]:
# Create Northern and Southern Hemisphere DataFrames

####  Northern Hemisphere - Max Temp vs. Latitude Linear Regression

####  Southern Hemisphere - Max Temp vs. Latitude Linear Regression

####  Northern Hemisphere - Humidity (%) vs. Latitude Linear Regression

####  Southern Hemisphere - Humidity (%) vs. Latitude Linear Regression

####  Northern Hemisphere - Cloudiness (%) vs. Latitude Linear Regression

####  Southern Hemisphere - Cloudiness (%) vs. Latitude Linear Regression

####  Northern Hemisphere - Wind Speed (mph) vs. Latitude Linear Regression

####  Southern Hemisphere - Wind Speed (mph) vs. Latitude Linear Regression